version: "3"
services:
  db:
    container_name: efrog-hub-database
    build:
      context: ../database
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD"]
      interval: 1s
      timeout: 1s
      retries: 1000

  app:
    container_name: efrog-hub-app
    build:
      context: ../
      dockerfile: ./app/Dockerfile
    environment:
      - DB_HOST=efrog-hub-database
      - DB_PORT=3306
    ports:
      - "1204:1204"
    depends_on:
        db:
          condition: service_healthy
    links:
          - db
    extra_hosts:
      - "host.docker.internal:host-gateway"