version: "3"
services:
    db:
        container_name: database
        build:
            context: ../database
            dockerfile: ./Dockerfile
        ports:
            - "5917:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root